@startuml
WAIT_RECEIVE --> CLOSE : ADMIN_CLOSE
WAIT_RECEIVE --> CLOSE : USER_CLOSE
NORMAL --> NORMAL : CREATE
NORMAL --> WAIT_RECEIVE : ADMIN_PUSH
NORMAL --> WAIT_RECEIVE : AUTO_PUSH
NORMAL --> CLOSE : ADMIN_CLOSE
@enduml